trigger:
  batch: true
  branches:
    include:
      - master
  tags:
    include:
      - '*'

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - docs/src/main/asciidoc/*
      - docs/src/main/asciidoc/images/*
      - README.md
      - CONTRIBUTING.md
      - LICENSE.txt
      - dco.txt
      - .github/ISSUE_TEMPLATE/*.md

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: test
    displayName: Test
    jobs:
      - job: unit_tests
        displayName: Unit tests
        pool:
          vmImage: ubuntu-16.04
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'
          - script: |
              yarn install
              yarn test --watchAll=false
            displayName: 'yarn install and test'
  - stage: build
    displayName: Build
    jobs:
      - job: build
        displayName: Build
        strategy:
          maxParallel: 2
          matrix:
            linux:
              imageName: 'ubuntu-16.04'
            windows:
              imageName: 'vs2017-win2016'
        pool:
          vmImage: $(imageName)
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'
          - script: |
              yarn install
              yarn build
            displayName: 'yarn install and build'
          - script: |
              yarn install
              yarn build:signer
            displayName: 'yarn install and build:signer'
